const GET_DATA = 'GET_DATA';
const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
const POST_DATA = 'POST_DATA';
const POST_DATA_SUCCESS = 'POST_DATA_SUCCESS';
const PUT_DATA = 'PUT_DATA';
const PATCH_DATA = 'PATCH_DATA';
const DELETE_DATA = 'DELETE_DATA';

export {
  GET_DATA,
  GET_DATA_SUCCESS,
  POST_DATA,
  POST_DATA_SUCCESS,
  PUT_DATA,
  PATCH_DATA,
  DELETE_DATA,
};
